WikeSoft.Web/Controllers/WorkFlow/FlowDesignController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Web.Mvc;
using WikeSoft.WorkFlowEngine;
using WikeSoft.WorkFlowEngine.Enum;
using WikeSoft.WorkFlowEngine.Filter;
using WikeSoft.WorkFlowEngine.Interfaces;
using WikeSoft.WorkFlowEngine.Models;

namespace WikeSoft.Web.Controllers.WorkFlow
{
    /// <summary>
    /// 
    /// </summary>
    public class FlowDesignController : BaseController
    {

     
        private readonly IWorkFlowDesignService _flowDesignService;
      
        /// <summary>
        /// 
        /// </summary>
        /// <param name="flowDesignService"></param>
        public FlowDesignController(IWorkFlowDesignService flowDesignService)
        {
            _flowDesignService = flowDesignService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult GetList(FlowDefFilter filter)
        {
            PagedResult<WorkFlowModel> defs=  _flowDesignService.GetList( filter);

            return JsonOk(defs);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Add()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(WorkFlowDefinition model)
        {
            if (ModelState.IsValid)
            {
                _flowDesignService.AddFlowDef(model);
                return RedirectToAction("Index");
            }
           
            return View();
        }

       /// <summary>
       /// 
       /// </summary>
       /// <param name="id"></param>
       /// <returns></returns>
        public ActionResult Edit(String id)
        {
            WorkFlowDefinition model = _flowDesignService.GetFlowDef(id);
            return View(model);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(WorkFlowDefinition model)
        {
            if (ModelState.IsValid)
            {
                bool flag = CeckHolidayApply(model.Id);
                if (flag)
                {
                    ViewBag.IsHoliday = true;
                    return View(model);
                }
                var flowMessage = _flowDesignService.UpdateFlowDef(model);
                if (flowMessage.Code == CodeEum.Success)
                    return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult FlowDesign()
        {
            return View();
        }
         
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public ActionResult Delete(IList<string> ids)
        {
            
            FlowMessage message = _flowDesignService.DeleteFlowDef(ids);
            if (message.Code == CodeEum.Success)
            {
                return Ok();
            }
            return Fail(message.Message);
        }


       /// <summary>
       /// 
       /// </summary>
       /// <param name="id"></param>
       /// <returns></returns>

        public ActionResult FlowDiagram(string id)
        {
            WorkFlowModel flow = _flowDesignService.GetFlowModel(id);
            return Json(flow, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="flowDef"></param>
        /// <returns></returns>
        public ActionResult SaveDiagram(WorkFlowModel flowDef)
        {
             bool flag = CeckHolidayApply(flowDef.Id);
            //flag = false;
            if (flag)
            {
                FlowMessage messageInstanse1 = new FlowMessage();
                messageInstanse1.Code = CodeEum.Fail;
                messageInstanse1.Message = "演示用例不能修改";
                return Json(messageInstanse1, JsonRequestBehavior.AllowGet);
            }
            FlowMessage messageInstanse = _flowDesignService.SaveDiagram(flowDef);
            return Json(messageInstanse, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="flowDef"></param>
        /// <returns></returns>
        public ActionResult SaveDiagramNew(WorkFlowModel flowDef)
        {
            bool flag = CeckHolidayApply(flowDef.Id);
            //flag = false;
            if (flag)
            {
                FlowMessage messageInstanse1 = new FlowMessage();
                messageInstanse1.Code = CodeEum.Fail;
                messageInstanse1.Message = "演示用例不能修改";
                return Json(messageInstanse1, JsonRequestBehavior.AllowGet);
            }
            FlowMessage messageInstanse = _flowDesignService.SaveDiagramWithNewVersion(flowDef);
            return Json(messageInstanse, JsonRequestBehavior.AllowGet);
        }

        private bool CeckHolidayApply(string defId)
        {

            if (defId.Equals("96F5B45A-6C94-4058-A76C-879FE6FFC09B"))
            {
                return true;
            }
            return false;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Pic(string id)
        {
            var image = _flowDesignService.GetBitmap(id);
            MemoryStream stream = new MemoryStream();
            image.Save(stream, ImageFormat.Jpeg);
            HttpContext.Response.Clear();
            HttpContext.Response.ContentType = "image/jpeg";
            HttpContext.Response.BinaryWrite(stream.ToArray());

        }
    }
}

WikeSoft.Web/Controllers/sys/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WikeSoft.Core.Exception;
using WikeSoft.Enterprise.Enum;
using WikeSoft.Enterprise.Interfaces.Sys;
using WikeSoft.Enterprise.Models.Filters.Sys;
using WikeSoft.Enterprise.Models.Sys;

namespace WikeSoft.Web.Controllers.Sys
{
    /// <summary>
    /// User
    /// </summary>
    public class UserController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        /// <summary>
        /// 
        /// </summary>
        /// <param name="userService"></param>
        /// <param name="roleService"></param>
        public UserController(IUserService userService, IRoleService roleService)
        {
            _userService = userService;
            _roleService = roleService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult FrameIndex()
        {
            return View();
        }





        /// <summary>
        /// 添加用户
        /// </summary>
        /// <returns></returns> 
        public ActionResult FrameAdd()
        {
            return View();
        }



        /// <summary>
        /// 添加用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FrameAdd(UserAddModel model)
        {
            if (ModelState.IsValid)
            {
                var success = _userService.Add(model);
                if (success)
                    return Redirect("/User/FrameIndex?departmentId=" + model.DepartmentId);
            }
            return View(model);
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <returns></returns> 
        public ActionResult FrameEdit(string id)
        {
            var model = _userService.Find(id);
            return View(model);
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FrameEdit(UserEditModel model)
        {
            if (ModelState.IsValid)
            {
                var success = _userService.Edit(model);
                if (success)
                    return Redirect("/User/FrameIndex?departmentId=" + model.DepartmentId);
            }
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: User
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// 添加用户
        /// </summary>
        /// <returns></returns> 
        public ActionResult Add()
        {
            return View();
        }



        /// <summary>
        /// 添加用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(UserAddModel model)
        {
            if (ModelState.IsValid)
            {
                var success = _userService.Add(model);
                if (success)
                    return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <returns></returns> 
        public ActionResult Edit(string id)
        {
            var model = _userService.Find(id);
            return View(model);
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(UserEditModel model)
        {
            if (ModelState.IsValid)
            {
                var success = _userService.Edit(model);
                if (success)
                    return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(IList<string> ids)
        {
            var success = _userService.Delete(ids);
            return success ? Ok() : Fail();
        }

        /// <summary>
        /// 判断用户名是否存在
        /// </summary>
        /// <returns></returns>
        [IgnorePasswordExpiration]
        public ActionResult IsExists(string Id, string UserName)
        {
            var exists = _userService.IsExists(Id, UserName);
            return JsonOk(!exists);
        }

        /// <summary>
        /// 判断员工编号是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userCode"></param>
        /// <returns></returns>
        [IgnorePasswordExpiration]
        public ActionResult IsExsitUserCode(string id, string userCode)
        {
            var exists = _userService.IsExsitUserCode(id, userCode);
            return JsonOk(!exists);
        }


        /// <summary>
        /// 验证密码是否是上一次的老密码
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [IgnorePasswordExpiration]
        public ActionResult IsOldPassword(ChangePasswordModel model)
        {
            var isOldPassword = _userService.IsOldPassword(User.Identity.GetLoginUserId(), model.Password);
            return JsonOk(!isOldPassword);
        }

        /// <summary>
        /// 验证旧密码是否输入正确
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [IgnorePasswordExpiration]
        public ActionResult IsPasswordCorrect(ChangePasswordModel model)
        {
            var isOldPassword = _userService.IsOldPassword(User.Identity.GetLoginUserId(), model.OldPassword);
            return JsonOk(isOldPassword);
        }

        /// <summary>
        /// 更改密码
        /// </summary>
        /// <returns></returns>
        [IgnorePasswordExpiration]
        public ActionResult ChangePassword()
        {

            var expirated = _userService.IsPasswordExpirated(User.Identity.GetLoginUserId());

            var user = _userService.Find(User.Identity.GetLoginUserId());
            ViewData["ExpiratedDate"] = user.PasswordExpirationDate;

            ViewData["IsPasswordExpirated"] = expirated;
            return View();
        }

        /// <summary>
        /// 更改密码
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [IgnorePasswordExpiration]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                model.UserId = User.Identity.GetLoginUserId();
                //throw new TipInfoException("禁止修改密码");
                var success = _userService.ChangePassword(model);
                if (success)
                    ViewBag.Sucess = true;
                else
                {
                    ViewBag.Sucess = false;
                }
            }
            return View(model);
        }

        /// <summary>
        /// 获取用户列表
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetList(UserFilter filter)
        {
            var users = _userService.GetUsers(filter);
            return JsonOk(users);
        }

        /// <summary>
        /// 加载角色部分视图
        /// </summary>
        /// <param name="id">用户Id</param>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult RolePartial(string id)
        {
            var roles = _roleService.GetAllRoles(id, RoleType.User);
            return PartialView("RolePartial", roles);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="departments"></param>
        /// <returns></returns>
        public ActionResult GetUsersByDepartment(List<string> departments)
        {
            List<UserModel> datas;
            if (departments != null)
            {
                datas = _userService.GetUsersByDepartment(departments);
            }
            else
            {
                datas = _userService.GetSubUsers(User.Identity.GetLoginUserId());
            }
           

            var list = datas.Select(x => new {x.Id,x.TrueName});

            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

WikeSoft.Web/Views/Shared/CloseLayerPartial.cshtml
<script>
    top.closeLayer();
</script>

WikeSoft.Web/Views/Shared/ExplorerError.cshtml
@{
    ViewBag.Title = "Page";
    Layout = null;
}

    <h3>致用户的一封信</h3>
    <div>
        <p>
            亲爱的用户，当您看到这个页面的时候，说明您使用的IE浏览器版本太低。
        </p>
        <p>
            我们的初衷是想兼容所有的浏览器，但是在开发的阶段，要兼容IE6、IE7几乎是不可能的。
        </p>
        <p>
            因此我们做出了一个非常艰难的决定，系统不再支持IE8以下的浏览器。
        </p>
        <p>
            为了给您带来更好的操作体验， 请您更换为其他的浏览器，以获得更好的浏览效果。
        </p>
        <p>
            我们推荐您使用FireFox、Google Chrome、Microsoft Edge、IE 9及以上的浏览器
        </p>
        <p>
            版权所有：惟科软件
        </p>
        
    </div>

WikeSoft.Web/Views/Shared/LicenseKey.cshtml
@using WikeSoft.Core
@using WikeSoft.Core.Security

@{
    ViewBag.Title = "Page";
    Layout = null;
    string mac = Mac.GetMacAddressByWmi();
    string key = DesEncrypt.Encode(mac);
}

    <h3>授权异常</h3>
    <div>
        <p>
            未授权或授权已过期，请联系授权人员，并将下面的<span style="color: red">授权码</span>提供给授权人员获得LicenseKey。
        </p>
        <p>
            授权码：<span style="color: red">@key</span>
        </p>
        <p>
            授权方式：将得到的LicenseKey加入到web.config的<span style="color:#337FE5;"><span><span style="font-family:Simsun;font-size:medium;">&lt;appSettings&gt;</span></span></span>节点下。
        </p>
        <p>
            <span style="color:#337FE5;"><span>&lt;add key="licensekey" value="你的LicenseKey</span><span>"/&gt;</span></span>
        </p>
        
        <p>
            版权所有：惟科软件
        </p>
        
    </div>

WikeSoft.Web/Views/Shared/NoRight.cshtml
@{
    Layout = "~/Views/Shared/_Form.cshtml";
    ViewBag.Title = "没有权限";

}
 

<div style="width: 100%">
    <fieldset>
        <legend>提示</legend>
    </fieldset>

    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>你没有访问权限</strong> 
    </div>


</div>

WikeSoft.Web/Views/Shared/Tip.cshtml
@model string
@{
    Layout = "~/Views/Shared/_Form.cshtml";
    ViewBag.Title = "Sorry, there was a problem!";
    String prevUrl=string.Empty;
    if (Request.UrlReferrer != null)
    {
        prevUrl = Request.UrlReferrer.ToString();
    }


}
<div  style="width: 100%">
    <fieldset>
        <legend>提示</legend>
    </fieldset>
  
    <div class="alert alert-warning alert-dismissible" role="alert">

        <strong>@Model</strong>
        @*@if (!string.IsNullOrEmpty(prevUrl))
        {
            <a href="@prevUrl" class="alert-link">点击返回</a>
            <br/>
            @prevUrl
        }*@
        
    </div>

   
</div>

WikeSoft.Web/Views/Shared/_AttachmentsPartial.cshtml
@using WikeSoft.Data.Interfaces
@using WikeSoft.Data.Models
@model  WikeSoft.Core.AttachmentSet

@{

    var attachmentService = DependencyResolver.Current.GetService<IAttachmentService>();
    List<AttachmentModel> attachments = new List<AttachmentModel>();
    if (Model.ObjectId.HasValue)
    {
        attachments = attachmentService.GetAttachmentsByObject(Model.ObjectId.Value, Model.GroupCode);
    }


}


<table class="table table-hover">
    <colgroup>
        <col width="auto">
        <col width="40px;">
        <col width="40px;">
    </colgroup>
    @for (int i = 0; i < attachments.Count; i++)
    {
        var responseData = attachments[i];
        if (responseData.IsImg)
        {
            <tr>
                <td><input class="attachment" type="hidden" name ="@Model.FiledName" value="@responseData.Id"/><a href="@responseData.UrlPath" target="_blank">@responseData.TrueName<img title="@responseData.TrueName" src="@responseData.ThumUrlPath" class="image-thum" style="width: 50px"/></a></td>
                <td><a target="_blank" href="/Attachment/Download?Id=@responseData.Id">下载</a></td>
                @if (Model.HaveRemove)
                {
                    <td><a href="#" onclick="delAttachment(this)">删除</a></td>
                }

            </tr>

        }
        else
        {
            <tr>
                <td><input class="attachment" type="hidden" name ="@Model.FiledName" value="@responseData.Id"/><a href="@responseData.UrlPath" target="_blank">@responseData.TrueName</a></td>
                <td><a target="_blank" href="/Attachment/Download?Id=@responseData.Id">下载</a></td>
                @if (Model.HaveRemove)
                {
                    <td><a href="#" onclick="delAttachment(this)">删除</a></td>
                }
            </tr>


        }
    }

</table>

<script type="text/javascript">
    //上传成功后的回调方法
    //loadId：上传控件的ID
    //responseData：上传成功后的响应数据
    function callBackData(loadId, responseData,fieldname) {
        if (responseData.IsImg) {
            $('<tr><td><input class="attachment" type="hidden" name="' + fieldname + '" value="' + responseData.Id + '" /><a href="' + responseData.UrlPath + '" target="_blank">' + responseData.TrueName + '<img  title="' + responseData.TrueName + '"  src="' + responseData.ThumUrlPath + '" style="width: 50px"  class="image-thum"/></a></td><td><a target="_blank" href="/Attachment/Download?Id=' + responseData.Id + '">下载</a></td><td><a href="#" onclick="delAttachment(this)">删除</a></td></tr>').appendTo($(loadId).next());
        } else {
            $('<tr><td><input class="attachment" type="hidden" name="' + fieldname + '" value="' + responseData.Id + '" /><a href="' + responseData.UrlPath + '" target="_blank">' + responseData.TrueName + '</a></td><td><a target="_blank" href="/Attachment/Download?Id=' + responseData.Id + '">下载</a></td><td><a href="#" onclick="delAttachment(this)">删除</a></td></tr>').appendTo($(loadId).next());
        }
    }

    function delAttachment(dom) {
        var id = $(dom).parent().parent().find("input:hidden").val();
      
        $.ajax({
            url: '/Attachment/DeleteAttachment',
            type: "POST",
            dataType: "json",
            data: JSON.stringify({ id: id }),
            contentType: "application/json, charset=utf-8",
            success: function (data) {
                
                if (data.success) {
                    $(dom).parent().parent().remove();
                } else {
                    top.layer.alert("删除失败：" + data.message);
                }
            }
        });
       
    }
</script>

WikeSoft.Web/Views/Shared/_FlowDesign.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>

    <!--css-->
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/jquery-ui-1.11.4.custom/jquery-ui.min.css" rel="stylesheet" />
    <link href="/Content/bootstrap-BootSideMenu/BootSideMenu.css" rel="stylesheet" />
    <link href="/Content/css/FactoryLayout/DragGraph.css" rel="stylesheet" />

    <!--js-->
    <script src="/Scripts/jquery-1.10.2.js"></script>
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Content/jquery-ui-1.11.4.custom/jquery-ui.js"></script>
    <script src="/Scripts/jsplumb.js"></script>
    <script src="/Content/bootstrap-BootSideMenu/BootSideMenu.js"></script>
    <script src="/Scripts/EwinCommon/EwinSelectArea.js"></script>
    <script src="/Scripts/PMCRule/Index.js"></script>
    <script src="~/Content/components/layer/layer.js"></script>



    <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
    <script>LA.init({ id: "JiNjx3UBDiqcMRub", ck: "JiNjx3UBDiqcMRub" })</script>

</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>

WikeSoft.Web/Views/Shared/_Foot.cshtml
@{
    ViewBag.Title = "_foot";
}

<div class="footer">
    <div class="footer-inner">
        <!-- #section:basics/footer -->
        <div class="footer-content">
            <span class="bigger-120">
                <span class="blue bolder">Ace</span>
                Application &copy; 2013-2014
            </span>

            &nbsp; &nbsp;
            <span class="action-buttons">
                <a href="#">
                    <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
                </a>

                <a href="#">
                    <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
                </a>

                <a href="#">
                    <i class="ace-icon fa fa-rss-square orange bigger-150"></i>
                </a>
            </span>
        </div>

        <!-- /section:basics/footer -->
    </div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
    <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>

WikeSoft.Web/Views/Shared/_Form.cshtml
@using System.Configuration
@*框架列表页面模版*@
@{
    string v = ConfigurationManager.AppSettings["version"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="format-detection" content="telephone=no" />
    <!--css-->

    <link href="~/Content/components/bootstrap/dist/css/bootstrap.css?v=@v" rel="stylesheet" />
    <link href="~/Content/components/font-awesome/css/font-awesome.min.css?v=@v" rel="stylesheet" />

    <link href="~/Content/wike.css" rel="stylesheet" />
    @RenderSection("styles", false)
    <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
    <script>LA.init({ id: "JiNjx3UBDiqcMRub", ck: "JiNjx3UBDiqcMRub" })</script>
</head>
<body>
    <div class="content-container" style="padding-top:10px;">
         
            @if (ViewBag.PageDes != null)
            {
                <div class="alert alert-success" role="alert">
                    @(new MvcHtmlString(ViewBag.PageDes))
                </div>
            }
            @RenderBody()
        
    </div>

    <script src="/Scripts/jquery-1.10.2.js?v=@v"></script>
    <script src="~/Content/components/bootstrap/dist/js/bootstrap.min.js?v=@v"></script>
    <script src="/Scripts/jquery.validate.js?v=@v"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js?v=@v"></script>
    <script src="/Scripts/jquery.unobtrusive-ajax.js?v=@v"></script>
    <script src="~/Scripts/json2.js?v=@v"></script>
    <script src="~/Content/My97DatePicker/WdatePicker.js?v=@v"></script>
    <script src="~/Scripts/respond.js?v=@v"></script>
    <script src="~/Content/components/html5shiv/dist/html5shiv.js?v=@v"></script>
    <script src="~/Scripts/jquery.placeholder.min.js?v=@v"></script>
    <script src="/Scripts/wike.extention.js?v=@v"></script>
    <script src="/Scripts/wike.action.js?v=@v"></script>
    <script src="/Scripts/wike.form.validate.js?v=@v"></script>
    <script src="~/Content/components/layer/layer.js?v=@v"></script>
    <script type="text/javascript">
        $(function () {
            $('input, textarea').placeholder();
        });
    </script>
    @RenderSection("scripts", false)
</body>
</html>

WikeSoft.Web/Views/Shared/_Head.cshtml
@using Star.Web
@using WikeSoft.Web
@{
    ViewBag.Title = "_Head";
}

<!-- #section:basics/navbar.layout -->
<div id="navbar" class="navbar navbar-default          ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <!-- #section:basics/sidebar.mobile.toggle -->
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>

        <!-- /section:basics/sidebar.mobile.toggle -->
        <div class="navbar-header pull-left">
            <!-- #section:basics/navbar.layout.brand -->
            <a href="#" class="navbar-brand">
                <small>
                     
                    @ViewBag.SystemTitle
                </small>
            </a>

            <!-- /section:basics/navbar.layout.brand -->
            <!-- #section:basics/navbar.toggle -->
            <!-- /section:basics/navbar.toggle -->
        </div>

        <!-- #section:basics/navbar.dropdown -->
        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
               
                 

                <!-- #section:basics/navbar.user_menu -->
                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        
                        <span class="user-info">
                            <small>您好,</small>
                            @User.Identity.GetTrueName()
                        </span>

                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>

                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#" targetlink="@Url.Action("ChangePassword", "User")">
                                <i class="ace-icon fa fa-cog"></i>
                                修改密码
                            </a>
                        </li>
                        <li class="divider"></li>

                        <li>
                            <a href="#" targetlink="@Url.Action("Logout", "Home")">
                                <i class="ace-icon fa fa-power-off"></i>
                                退出
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- /section:basics/navbar.user_menu -->
            </ul>
        </div>

        <!-- /section:basics/navbar.dropdown -->
    </div><!-- /.navbar-container -->
</div>


<script type="text/javascript">

    $(function() {
        getMyUnReadTaskWakeCount();
    });


    function getMyUnReadTaskWakeCount() {
        $.ajax({
            url: '/TaskWake/GetMyUnReadTaskWakeCount',
            type: "GET",
            dataType: "json",
            
            contentType: "application/json, charset=utf-8",
            success: function (data) {
                $("#totalMsg").html(data);
                $("#taskWake").html(data);
            }
        });
    }
</script>