WikeSoft.Web/Controllers/WorkFlow/WorkFlowInstanceController.cs
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Web.Mvc;
using WikeSoft.WorkFlowEngine.Enum;
using WikeSoft.WorkFlowEngine.Filter;
using WikeSoft.WorkFlowEngine.Interfaces;
using WikeSoft.WorkFlowEngine.Models;

namespace WikeSoft.Web.Controllers.WorkFlow
{
    /// <summary>
    /// 
    /// </summary>
    public class WorkFlowInstanceController : BaseController
    {
        private IWorkFlowInstanceService _workFlowInstanceService;
        private readonly IWorkFlowInstanceService _flowInstanceService;
        /// <summary>
        /// 
        /// </summary>
        /// <param name="workFlowInstanceService"></param>
        /// <param name="flowInstanceService"></param>
        public WorkFlowInstanceController(IWorkFlowInstanceService workFlowInstanceService, IWorkFlowInstanceService flowInstanceService)
        {
            _workFlowInstanceService = workFlowInstanceService;
            _flowInstanceService = flowInstanceService;
        }

        // GET: WorkFlowInstance
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult HistoryInstanceView()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>

        [HttpGet]
        public JsonResult Query(WorkFlowInstanceFilter filter)
        {
            var result = _workFlowInstanceService.Query(filter);
            return JsonOk(result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult QueryHistory(WorkFlowInstanceFilter filter)
        {
            filter.AssociatedUserId = User.Identity.GetLoginUserId().ToString().ToUpper();
            var result = _workFlowInstanceService.Query(filter);
            return JsonOk(result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="instanceId"></param>
        /// <returns></returns>
        public ActionResult GetTaskView( string instanceId)
        {

            List<TaskInstance> flows = _flowInstanceService.GetHistoryFlowInstances(instanceId);
            ViewBag.Historys = flows;
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult WaitToDoList()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult QueryWaitToDoList(WorkFlowInstanceFilter filter)
        {
            filter.AssociatedUserId = User.Identity.GetLoginUserId().ToString().ToUpper();
            filter.FlowRunStatus = FlowRunStatus.Run;
            
            var result = _workFlowInstanceService.Query(filter);
            return JsonOk(result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="flowId"></param>
        public void Pic(string flowId)
        {
            var image = _flowInstanceService.GetRunBitmap(flowId);
            MemoryStream stream = new MemoryStream();
            image.Save(stream, ImageFormat.Jpeg);
            HttpContext.Response.Clear();
            HttpContext.Response.ContentType = "image/jpeg";
            HttpContext.Response.BinaryWrite(stream.ToArray());

        }
    }
}

WikeSoft.Web/Views/WorkFlowInstance/GetTaskView.cshtml
@using WikeSoft.WorkFlowEngine.Entities
@using WikeSoft.WorkFlowEngine.Models

@{
    ViewBag.Title = "调证审核";
    Layout = "~/Views/Shared/_Form.cshtml";
    String prevUrl = string.Empty;
    string instanceId = Request["instanceId"];
    if (Request.UrlReferrer != null)
    {
        prevUrl = Request.UrlReferrer.ToString();
    }
}


@section scripts{
    <script type="text/javascript">


        function setCondition(val) {
            $("#Condition").val(val);
            return true;
        }


    </script>

}


@if (ViewBag.Historys != null && ViewBag.Historys.Count > 0)
{
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label class="col-sm-2 control-label">处理记录</label>
            <div class="col-sm-10">
                <table class="table table-striped">
                    <tr>
                        <th>操作环节</th>
                        <th>处理人</th>
                        <th>时间</th>
                        <th>处理意见</th>
                    </tr>

                    @foreach (TaskInstance data in ViewBag.Historys)
                        {
                        <tr>
                            <td>@data.NodeDefName</td>
                            <td>@data.DealUser</td>
                            <td>@(data.DealDate.HasValue ? data.DealDate.Value.ToString("yyyy-MM-dd HH:mm:ss") : "")</td>
                            <td>@data.DealRemark</td>
                        </tr>
                        }

                </table>

            </div>
        </div>

    </form>
}



<form class="form-horizontal" method="post">


    <div class="form-group">
        <label class="col-sm-2 control-label">流程图</label>
        <div class="col-sm-10">
            <div class="form-group">
                <img src="@Url.Action("Pic","WorkFlowInstance")?flowId=@instanceId&r=@Guid.NewGuid().ToString()" />
            </div>

        </div>
    </div>

</form>

WikeSoft.Web/Views/WorkFlowInstance/HistoryInstanceView.cshtml
@{
    ViewBag.Title = "流程管理";
    Layout = "~/Views/Shared/_FrameLayout.cshtml";
    string categoryId = Request["CategoryId"];
}
@section scripts
{


    <script>


        function formatterInstance(cellvalue, options, rowObject) {
            //return "<a style='color:red' href='/CustomerCertificate/CustomerAndCertificateReadOnlyView?id=" + rowObject.Id + "'>" + cellvalue + "</a>";
            //if (rowObject.BusinessPath != "" && rowObject.BusinessPath != null) {
            //    return cellvalue;
            //}
            return "<a style='color:red' href='#' onclick='openBusinessModel(\"" + rowObject.BusinessPath + "\")'>" + cellvalue + "</a>";
        }


        function openBusinessModel(businessPath) {
            top.layer.open({
                title: '业务数据',
                type: 2,
                content: businessPath,
                area: ['1100px', '620px'],
                cancel: function(index, layero) {
                    WikePage.ReLoadCurrentPage();
                    top.layer.close(index);
                }

            });
        }


        $(document).ready(function() {
            var config = {
                title: '流程管理',
                url: '@Url.Action("QueryHistory")?categoryId=@categoryId',
                colNames: ['主键', '实例名称', '创建人', '创建时间', '所属类别', '业务路径'],
                colModel: [
                    { name: 'Id', index: 'Id', width: 60, key: true, hidden: true },
                    { name: 'InstanceName', index: 'InstanceName', width: 100, formatter: formatterInstance },
                    { name: 'CreateUser', index: 'CreateUser', width: 30 },
                    { name: 'CreateTime', index: 'CreateTime', width: 30, formatter: 'date', formatoptions: { srcformat: 'Y-m-d H:i:s', newformat: 'Y-m-d H:i:s' } },
                    { name: 'CategoryName', index: 'CategoryName', width: 30 },
                    { name: 'BusinessPath', index: 'BusinessPath', width: 30, hidden: true }
                ],
                sortname: 'CreateTime',
                sortorder: "desc"
            };
            WikeGrid.Load(config);
        });
    </script>
}


<form id="searchToolBar" class="alert alert-info form-inline toolbarsearch" action="">
    <div class="form-group">
        <input type="text" id="keywords" name="keywords" autocomplete="off" class="form-control" placeholder="请输入关键字" />
    </div>
    <button class="btn btn-danger" id="btnSearch" type="button">
        <i class="fa menu-icon fa-cog "></i>查询
    </button>
   
</form>
<div class="jqGrid_wrapper">
    <table id="table_list"></table>
    <div id="pager_list"></div>
</div>

WikeSoft.Web/Views/WorkFlowInstance/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

WikeSoft.Web/Views/WorkFlowInstance/WaitToDoList.cshtml
@{
    ViewBag.Title = "流程管理";
    Layout = "~/Views/Shared/_FrameLayout.cshtml";
    string categoryId = Request["CategoryId"];
}
@section scripts
{


    <script>


        function formatterInstance(cellvalue, options, rowObject) {
            //return "<a style='color:red' href='/CustomerCertificate/CustomerAndCertificateReadOnlyView?id=" + rowObject.Id + "'>" + cellvalue + "</a>";
            return "<a style='color:red' href='#' onclick='openBusinessModel(\"" + rowObject.BusinessPath + "\")'>" + cellvalue + "</a>";
        }


        function openBusinessModel(businessPath) {
            top.layer.open({
                title: '业务数据',
                type: 2,
                content: businessPath,
                area: ['1000px', '700px'],
                cancel: function (index, layero) {
                    WikePage.ReLoadCurrentPage();
                    top.layer.close(index);
                }


            });
        }


        $(document).ready(function() {
            var config = {
                title: '流程管理',
                url: '@Url.Action("QueryWaitToDoList")?categoryId=@categoryId',
                colNames: ['主键', '实例名称', '创建人', '创建时间','所属类别','业务路径'],
                colModel: [
                    { name: 'Id', index: 'Id', width: 60, key: true, hidden: true },
                    { name: 'InstanceName', index: 'InstanceName', width: 30, formatter: formatterInstance },
                    { name: 'CreateUser', index: 'CreateUser', width: 30 },
                    { name: 'CreateTime', index: 'CreateTime', width: 30, formatter: 'date', formatoptions: { srcformat: 'Y-m-d H:i:s', newformat: 'Y-m-d H:i:s' } },
                    { name: 'CategoryName', index: 'CategoryName', width: 30  },
                    { name: 'BusinessPath', index: 'BusinessPath', width: 30,hidden:true }

                ],
                sortname: 'CreateTime',
                sortorder: "desc"
            };
            WikeGrid.Load(config);
        });
    </script>
}


<form id="searchToolBar" class="alert alert-info form-inline toolbarsearch" action="">
    <div class="form-group">
        <input type="text" id="keywords" name="keywords" autocomplete="off" class="form-control" placeholder="请输入关键字" />
    </div>
    <button class="btn btn-danger" id="btnSearch" type="button">
        <i class="fa menu-icon fa-cog "></i>查询
    </button>

</form>
<div class="jqGrid_wrapper">
    <table id="table_list"></table>
    <div id="pager_list"></div>
</div>